//
//  Cities.swift
//  WeatherApp
//
//  Created by Levchuk Misha on 15.12.2017.
//  Copyright © 2017 Levchuk Misha. All rights reserved.
//

import Foundation

class Cities {
    var citiesArray = [String]()
    init() {
        citiesArray =
        [
            "Kinshasa",
            "Alexandria",
            "Cairo",
            "Addis Ababa",
            "Abidjan",
            "Mombasa",
            "Nairobi",
            "Casablanca",
            "Windhoek",
            "Ibadan",
            "Kano",
            "Lagos",
            "Cape Town",
            "Durban",
            "Johannesburg",
            "Dhaka",
            "Beijing",
            "Chengdu",
            "Dongguan",
            "Guangzhou",
            "Hangzhou",
            "Hong Kong",
            "Shanghai",
            "Shenzhen",
            "Tianjin",
            "Wuhan",
            "Ahmedabad",
            "Bangalore",
            "Chennai",
            "Hyderabad",
            "Kolkata",
            "Mumbai",
            "New Delhi",
            "Pune",
            "Surat",
            "Denpasar",
            "Jakarta",
            "Tehran",
            "Baghdad",
            "Fukuoka",
            "Hiroshima",
            "Kawasaki",
            "Kitakyushu",
            "Kobe",
            "Kyoto",
            "Nagoya",
            "Osaka",
            "Saitama",
            "Sapporo",
            "Sendai",
            "Tokyo",
            "Yokohama",
            "Kuala Lumpur",
            "Yangon",
            "Pyongyang",
            "Karachi",
            "Lahore",
            "Manila",
            "Riyadh",
            "Singapore",
            "Busan",
            "Seoul",
            "Damascus",
            "Taipei",
            "Bangkok",
            "Phuket",
            "Ankara",
            "Istanbul",
            "Izmir",
            "Dubai",
            "Ho Chi Minh City",
            "Ha Noi",
            "Adelaide",
            "Brisbane",
            "Melbourne",
            "Perth",
            "Sydney",
            "Auckland",
            "Christchurch",
            "Manukau",
            "Wellington",
            "Vienna",
            "Minsk",
            "Brussels",
            "Sofia",
            "Zagreb",
            "Prague",
            "Copenhagen",
            "Helsinki",
            "Ajaccio",
            "Bordeaux",
            "Calvi",
            "Lille",
            "Lyon",
            "Marseille",
            "Nice",
            "Paris",
            "Toulouse",
            "Berlin",
            "Bremen",
            "Cologne",
            "Dortmund",
            "Dresden",
            "Dusseldorf",
            "Essen",
            "Frankfurt",
            "Hamburg",
            "Hanover",
            "Leipzig",
            "Munich",
            "Nuremberg",
            "Stuttgart",
            "Athens",
            "Santorini",
            "Budapest",
            "Reykjavik",
            "Dublin",
            "Milan",
            "Naples",
            "Rome",
            "Torino",
            "Venice",
            "Amsterdam",
            "The Hague",
            "Oslo",
            "Warsaw",
            "Lisbon",
            "Bucharest",
            "Moscow",
            "St Petersburg",
            "Barcelona",
            "Madrid",
            "Santa Cruz de Tenerife",
            "Santander",
            "Gothenburg",
            "Stockholm",
            "Geneva",
            "Zurich",
            "Kharkiv",
            "Kiev",
            "Birmingham",
            "Blackpool",
            "Bournemouth",
            "Bradford",
            "Brighton",
            "Bristol",
            "Cambridge",
            "Coventry",
            "Derby",
            "Exeter",
            "Falmouth",
            "Huddersfield",
            "Ipswich",
            "Kingston upon Hull",
            "Leeds",
            "Leicester",
            "Liverpool",
            "London",
            "Luton",
            "Manchester",
            "Middlesbrough",
            "Newcastle",
            "Northampton",
            "Norwich",
            "Nottingham",
            "Oxford",
            "Penzance",
            "Plymouth",
            "Portsmouth",
            "Preston",
            "Reading",
            "Salford",
            "Sheffield",
            "Southend-on-Sea",
            "St Ives",
            "Stoke-on-Trent",
            "Sunderland",
            "Swindon",
            "Truro",
            "Wakefield",
            "Wolverhampton",
            "York",
            "Belfast",
            "Aberdeen",
            "Dundee",
            "Edinburgh",
            "Glasgow",
            "Cardiff",
            "Swansea",
            "Calgary",
            "Edmonton",
            "Montreal",
            "Toronto",
            "Vancouver",
            "Mexico City",
            "Birmingham USA",
            "Anchorage",
            "Mesa",
            "Phoenix",
            "Tucson",
            "Little Rock",
            "Bakersfield",
            "Fresno",
            "Lake Tahoe",
            "Long Beach",
            "Los Angeles",
            "Mountain View",
            "Oakland",
            "Palm Springs",
            "Sacramento",
            "San Diego",
            "San Francisco",
            "San Jose",
            "Santa Cruz",
            "Boulder",
            "Colorado Springs",
            "Denver",
            "Bridgeport",
            "Wilmington",
            "Washington DC",
            "Jacksonville",
            "Miami",
            "Atlanta",
            "Honolulu",
            "Boise",
            "Chicago",
            "Indianapolis",
            "Des Moines",
            "Wichita",
            "Louisville",
            "New Orleans",
            "Portland",
            "Baltimore",
            "Boston",
            "Detroit",
            "Minneapolis",
            "Jackson",
            "Kansas City",
            "St. Louis",
            "Billings",
            "Omaha",
            "Las Vegas",
            "Manchester",
            "Newark",
            "Albuquerque",
            "Santa Fe",
            "New York",
            "Charlotte",
            "Raleigh",
            "Fargo",
            "Columbus",
            "Oklahoma City",
            "Portland",
            "Philadelphia",
            "Providence",
            "Columbia",
            "Sioux Falls",
            "Memphis",
            "Nashville",
            "Austin",
            "Salt Lake City",
            "Burlington",
            "Richmond",
            "Virginia Beach",
            "Seattle",
            "Charleston",
            "Milwaukee",
            "Cheyenne",
            "Buenos Aires",
            "Brasilia",
            "Rio de Janeiro",
            "Salvador",
            "Sao Paulo",
            "Santiago",
            "Bogota",
            "Lima",
            "Caracas",
            "Maracaibo"



            
        ]
    }


}
